#ifndef PBCCHAIN_CHAINPARAMSSEEDS_H
#define PBCCHAIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the pbcchain network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside an IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,95,128,26,17}, 6704}
};

static SeedSpec6 pnSeed6_test[] = {
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,95,128,26,17}, 16704}
};
#endif // PBCCHAIN_CHAINPARAMSSEEDS_H
